# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Build settings
markdown: kramdown
plugins:
  - jekyll-postcss

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
destination: public
exclude:
  - .gitignore
  - .jekyll-cache/
  - .sass-cache/
  - bin
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - netlify.toml
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - public/
  - purgecss.config.js
  - README.md
  - tailwind.config.js
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - webpack.config.js
  - webpack/
  - yarn.lock
